namespace Hamco.Core.Models;

/// <summary>
/// Represents a blog note (post) in the system.
/// This is the main content entity that users create, read, update, and delete.
/// </summary>
/// <remarks>
/// Maps to the 'notes' table in PostgreSQL database.
/// 
/// Design decisions:
/// - Uses int for Id (auto-incrementing primary key) for simplicity
/// - UserId is nullable to allow anonymous posts during development
/// - DeletedAt field supports soft delete pattern (not currently used)
/// - Slug is auto-generated from Title for SEO-friendly URLs
/// 
/// This model matches the Django Note model from the original hamco-python project.
/// Key differences from Django:
/// - C# requires explicit property declarations (Django uses implicit fields)
/// - Default values set with property initializers (= string.Empty)
/// - Navigation property (User) explicitly defined for Entity Framework
/// </remarks>
public class Note
{
    /// <summary>
    /// Primary key. Auto-incremented by PostgreSQL.
    /// </summary>
    /// <remarks>
    /// In C#, 'int' is a 32-bit signed integer (range: -2.1B to 2.1B).
    /// Entity Framework configures this as SERIAL in PostgreSQL.
    /// This property is set by the database after insert.
    /// </remarks>
    public int Id { get; set; }
    
    /// <summary>
    /// The note title. Required field, max 255 chars.
    /// Used to auto-generate the URL-friendly slug.
    /// </summary>
    /// <remarks>
    /// Default value 'string.Empty' prevents null reference warnings.
    /// In C#, 'string.Empty' is equivalent to "" but more explicit.
    /// Validation enforced via CreateNoteRequest and UpdateNoteRequest DTOs.
    /// </remarks>
    public string Title { get; set; } = string.Empty;
    
    /// <summary>
    /// URL-friendly version of the title (e.g., "my-blog-post").
    /// Auto-generated by SlugGenerator when creating/updating notes.
    /// </summary>
    /// <remarks>
    /// Slugs are used in URLs: /posts/my-blog-post
    /// Examples:
    ///   "Hello World" → "hello-world"
    ///   "C# Tips & Tricks!" → "c-tips-tricks"
    /// 
    /// Generated automatically - users don't provide this value.
    /// Max length 255 characters to match database constraint.
    /// </remarks>
    public string Slug { get; set; } = string.Empty;
    
    /// <summary>
    /// The main content of the note. Supports markdown formatting.
    /// </summary>
    /// <remarks>
    /// No max length constraint - stored as TEXT in PostgreSQL.
    /// In C#, 'string' can hold up to 2GB of text (practical limit).
    /// Future: Could add markdown-to-HTML rendering.
    /// </remarks>
    public string Content { get; set; } = string.Empty;
    
    /// <summary>
    /// ID of the user who created this note. Nullable for anonymous posts.
    /// </summary>
    /// <remarks>
    /// The '?' makes this nullable (C# 8+ nullable reference types).
    /// Currently set to null because authentication is not enforced.
    /// 
    /// In C#:
    ///   - 'string' = non-nullable (must have a value)
    ///   - 'string?' = nullable (can be null)
    /// 
    /// Future: When auth is enforced, this will be populated from JWT token.
    /// </remarks>
    public string? UserId { get; set; }
    
    /// <summary>
    /// UTC timestamp when this note was created.
    /// </summary>
    /// <remarks>
    /// 'DateTime.UtcNow' gets current UTC time (not local time).
    /// Always use UTC for stored timestamps to avoid timezone issues.
    /// 
    /// Default value set here, but database also has DEFAULT CURRENT_TIMESTAMP.
    /// This ensures CreatedAt is set even if not explicitly assigned.
    /// </remarks>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    
    /// <summary>
    /// UTC timestamp when this note was last updated.
    /// </summary>
    /// <remarks>
    /// Updated automatically in controller when PUT /api/notes/{id} is called.
    /// Initially set to same value as CreatedAt.
    /// </remarks>
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
    
    /// <summary>
    /// UTC timestamp when this note was soft-deleted. Null if not deleted.
    /// </summary>
    /// <remarks>
    /// 'DateTime?' is a nullable value type (struct can be null).
    /// 
    /// Soft delete pattern: Instead of removing row from database,
    /// set DeletedAt = DateTime.UtcNow to mark as deleted.
    /// 
    /// Benefits:
    ///   - Can restore deleted items
    ///   - Preserves historical data
    ///   - Maintains referential integrity
    /// 
    /// ⚠️ CURRENT STATUS: Field exists but hard delete is used.
    /// To use soft delete, modify DeleteNote action in controller.
    /// </remarks>
    public DateTime? DeletedAt { get; set; }
    
    /// <summary>
    /// Navigation property to the User who created this note.
    /// Used by Entity Framework for relationships.
    /// </summary>
    /// <remarks>
    /// Navigation properties in EF Core:
    ///   - Not stored in database (virtual relationship)
    ///   - Populated when you use .Include() in queries
    ///   - Nullable because UserId is nullable
    /// 
    /// Example query:
    ///   var notes = await _context.Notes
    ///       .Include(n => n.User)  // Load related user
    ///       .ToListAsync();
    /// 
    /// Without .Include(), this property will be null even if UserId has a value.
    /// </remarks>
    public User? User { get; set; }
}
